export const GET_MESSAGES = "GET_MESSAGES";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_MSG_IDS_ARRAY = "SET_MSG_IDS_ARRAY";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const CHANGE_SEARCH_INPUT = "CHANGE_SEARCH_INPUT";
